[package]
name = "todo"
version = "0.1.0"
edition = "2024"

[dependencies]
argh = "0.1.13"
const_format = "0.2.34"
env_logger = "0.11.8"
glob = "0.3.2"
inquire = "0.7.5"
log = "0.4.27"
tinyvec = { version = "1.9.0", features = ["alloc", "rustc_1_61"] }
